name: Run News Script

on:
  schedule:
    - cron: "0 7,21 * * *"  # كل يوم الساعة 7 صباحًا و9 مساءً UTC
  workflow_dispatch:

jobs:
  run-news-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run news.py
        run: python news.py
